-- MySQL Script generated by MySQL Workbench
-- Tue Sep  1 09:48:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `CPF` CHAR(14) NOT NULL,
  PRIMARY KEY (`id`, `nome`, `CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sgila` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sgila_UNIQUE` (`sgila` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Passeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Passeio` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Hospedagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Hospedagem` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Estado` (
  `Pessoa_id` INT NOT NULL,
  `Estado_id` INT NOT NULL,
  PRIMARY KEY (`Pessoa_id`, `Estado_id`),
  INDEX `fk_Pessoa_has_Estado_Visitado_Estado_Visitado1_idx` (`Estado_id` ASC) VISIBLE,
  INDEX `fk_Pessoa_has_Estado_Visitado_Pessoa_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_has_Estado_Visitado_Pessoa`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Estado_Visitado_Estado_Visitado1`
    FOREIGN KEY (`Estado_id`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Tipo_Passeio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Tipo_Passeio` (
  `Pessoa_id` INT NOT NULL,
  `Tipo_Passeio_id` INT NOT NULL,
  PRIMARY KEY (`Pessoa_id`, `Tipo_Passeio_id`),
  INDEX `fk_Pessoa_has_Tipo_Passeio_Tipo_Passeio1_idx` (`Tipo_Passeio_id` ASC) VISIBLE,
  INDEX `fk_Pessoa_has_Tipo_Passeio_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_has_Tipo_Passeio_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Tipo_Passeio_Tipo_Passeio1`
    FOREIGN KEY (`Tipo_Passeio_id`)
    REFERENCES `mydb`.`Tipo_Passeio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Tipo_Hospedagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Tipo_Hospedagem` (
  `Pessoa_id` INT NOT NULL,
  `Tipo_Hospedagem_id` INT NOT NULL,
  PRIMARY KEY (`Pessoa_id`, `Tipo_Hospedagem_id`),
  INDEX `fk_Pessoa_has_Tipo_Hospedagem_Tipo_Hospedagem1_idx` (`Tipo_Hospedagem_id` ASC) VISIBLE,
  INDEX `fk_Pessoa_has_Tipo_Hospedagem_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_has_Tipo_Hospedagem_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Tipo_Hospedagem_Tipo_Hospedagem1`
    FOREIGN KEY (`Tipo_Hospedagem_id`)
    REFERENCES `mydb`.`Tipo_Hospedagem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
