/** script do curso de banco de dados MySQL utilizando workbench**/

DROP DATABASE IF EXISTS AULA_BANCO;	/** caso exista, eliminando a base de dados AULA_BANCO **/
CREATE DATABASE AULA_BANCO; 		/** criando a base de dados **/
USE AULA_BANCO;				/** selecionando a base de dados **/


/** criando tabelas **/
CREATE TABLE ESTADO(
ID INT AUTO_INCREMENT
,NOME VARCHAR(255) NOT NULL UNIQUE 
,SIGLA CHAR(2) NOT NULL UNIQUE 
,STATUS CHAR(1) NOT NULL DEFAULT 'A' 
,DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
,CONSTRAINT PK_ESTADO PRIMARY KEY (ID) 
);

CREATE TABLE CIDADE(
ID INT AUTO_INCREMENT 
,NOME VARCHAR(255) NOT NULL 
,STATUS CHAR(1) NOT NULL DEFAULT 'A' 
,ESTADO_ID INT NOT NULL
,DATA_CADASTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
,CONSTRAINT PK_CIDADE PRIMARY KEY (ID) 
,CONSTRAINT FK_CID_EST FOREIGN KEY (ESTADO_ID) REFERENCES ESTADO (ID)
,CONSTRAINT FK_CID_UNIQUE UNIQUE(NOME,ESTADO_ID)
);

/** inserindo registros **/
INSERT INTO ESTADO (NOME,SIGLA) VALUES ('PARANÁ','PR');
INSERT INTO ESTADO (NOME,SIGLA) VALUES ('SÃO PAULO','SP');
INSERT INTO ESTADO (NOME,SIGLA) VALUES ('MATO GROSSO','MT');
INSERT INTO ESTADO (NOME,SIGLA) VALUES ('SANTA CATARINA','SC');
INSERT INTO ESTADO (NOME,SIGLA) VALUES ('RIO GRANDE DO SUL','RS');

INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('BAURU',2);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('MARINGÁ',1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('GUARULHOS',2);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('CAMPINAS',2);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('FLORIANÓPOLIS',4);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('PARANAVAÍ',1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('CUIABA',3);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('BALNEÁRIO CAMBORIÚ',4);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('LONDRINA',1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('CASCAVEL',1);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('JOINVILLE',4);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('PORTO ALEGRE',5);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('BLUMENAL',4);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('BARRA DOS GARÇAS',3);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('CHAPECÓ',4);
INSERT INTO CIDADE (NOME, ESTADO_ID) VALUES ('ITAJAÍ',4);

/** consutla estado **/
SELECT * FROM ESTADO;

/** consutla cidade **/
SELECT * FROM CIDADE;

/** SELECT SIGLA FROM ESTADO WHERE ID = ??**/

/** CRIANDO FUNÇÃO QUE TEM COMO PARÂMETRO, O CÓDIGO DO ESTADO E RETORNA A SIGLA DO ESTADO **/
DELIMITER //
CREATE FUNCTION buscar_sigla_estado(id_estado INT)
RETURNS CHAR(2) DETERMINISTIC 
BEGIN 
	DECLARE resultado CHAR(2);
    SELECT sigla INTO resultado FROM estado WHERE id = id_estado;
    RETURN resultado;
END;
//
DELIMITER ;

SELECT buscar_sigla_estado(3);
SELECT nome,estado_id FROM cidade WHERE id = 1;
SELECT nome, buscar_sigla_estado(estado_id) FROM cidade WHERE id = 1;

SELECT nome,estado_id FROM cidade;


SELECT nome, buscar_sigla_estado(estado_id) FROM cidade;

SELECT c.nome, e.sigla
FROM estado e, cidade c
WHERE e.id = c.estado_id;

SELECT COUNT(id) FROM cidade WHERE estado_id = 2;

/** função que conta cidades de ume estado **/
DELIMITER //
CREATE FUNCTION contar_cidade(id_estado INT)
RETURNS INT DETERMINISTIC 
BEGIN
	DECLARE resultado INT;
    SELECT COUNT(id) INTO resultado FROM cidade WHERE estado_id = id_estado;
    RETURN resultado;
END;
//
DELIMITER ;

SELECT contar_cidade(2);
SELECT nome, id FROM estado WHERE id = 1;
SELECT nome 'Estado', contar_cidade(id) 'Quantidade de Cidades' FROM estado WHERE id = 1;


SELECT nome, id FROM estado;
SELECT nome 'Estado', contar_cidade(id) 'Quantidade de Cidades' FROM estado;

SELECT e.nome, COUNT(c.id)
FROM estado e, cidade c
WHERE e.id = c.estado_id
GROUP BY e.id;


